spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    drover-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.postgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: LJ
    password: LJ
    properties:
      mail:
        smtp:
          trust: "*"
        auth: truth
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000